version: '3'
services:
  discoveryservice:
    build: discoveryservice
    image: discoveryservice:latest
    ports:
      - 8761:8761
    restart: always
    depends_on: 
      - configservice
    entrypoint:
      - ./wait
      - configservice:8888
      - -t
      - "300"
      - --
      - java
      - -jar
      - /usr/exec/app.jar

  configservice:
    build: configservice
    image: configservice:latest
    ports:
      - 8888:8888
    restart: always

  apigateway:
    build: apigateway
    image: apigateway:latest
    ports:
      - 9091:9091
    depends_on:
      - configservice
    restart: always
    entrypoint:
      - ./wait
      - discoveryservice:8761
      - -t
      - "300"
      - --
      - java
      - -jar
      - usr/exec/app.jar

  helloservice:
    build: helloservice
    image: helloservice:latest
    ports:
      - 8081:8081
    depends_on:
      - configservice
    restart: always
    entrypoint:
      - ./wait
      - discoveryservice:8761
      - -t
      - "300"
      - --
      - java
      - -jar
      - usr/exec/app.jar

  module1:
    build:
      context: ./multimodule/
    image: module1:latest
    ports:
      - 4000:4000
    entrypoint:
      - ./wait
      - discoveryservice:8761
      - -t
      - "300"
      - --
      - java
      - -jar
      - /usr/app/exec/app.jar

  webapp:
    build: webapp
    image: webapp:latest
    ports:
      - 8200:8200
    restart: always
    depends_on:
      - configservice
    entrypoint:
      - ./wait
      - discoveryservice:8761
      - -t
      - "300"
      - --
      - java
      - -jar
      - /webappserver/target/app.jar